### ISSUE TITLE
Timeout al modificar corrida programada

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#13]
Al reiniciar el sistema e intentar modificar la configuración usando la GUI (http://localhost:5000/view/schedule_tasks/2), queda colgado esperando respuesta del servidor (Timeout). 
Y por lo general está muy lenta la GUI
Aparentemente la cadena de LEFT OUTER JOINS del query genera una respuesta bastante pesada (234780 filas)

En el log del container web:

    [2023-12-13 18:49:21 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:92)
    [2023-12-13 18:49:21 +0000] [92] [INFO] Worker exiting (pid: 92) 
    [2023-12-13 18:49:22 +0000] [8] [WARNING] Worker with pid 92 was terminated due to signal 9
    [2023-12-13 18:49:22 +0000] [146] [INFO] Booting worker with pid: 146

Y en el log del container database:
    
    2023-12-13 18:48:51.579 UTC [118] LOG:  could not send data to client: Connection reset by peer
    2023-12-13 18:48:51.579 UTC [118] STATEMENT:  SELECT anon_1.gesina_scheduled_task_metadata AS anon_1_gesina_scheduled_task_metadata, anon_1.gesina_scheduled_task_id AS anon_1_gesina_scheduled_task_id, anon_1.gesina_scheduled_task_name AS anon_1_gesina_scheduled_task_name, anon_1.gesina_scheduled_task_description AS anon_1_gesina_scheduled_task_description, anon_1.gesina_scheduled_task_frequency AS anon_1_gesina_scheduled_task_frequency, anon_1.gesina_scheduled_task_created_at AS anon_1_gesina_scheduled_task_created_at, anon_1.gesina_scheduled_task_start_datetime AS anon_1_gesina_scheduled_task_start_datetime, anon_1.gesina_scheduled_task_enabled AS anon_1_gesina_scheduled_task_enabled, anon_1.gesina_scheduled_task_geometry_id AS anon_1_gesina_scheduled_task_geometry_id, anon_1.gesina_scheduled_task_user_id AS anon_1_gesina_scheduled_task_user_id, anon_1.gesina_scheduled_task_start_condition_type AS anon_1_gesina_scheduled_task_start_condition_type, anon_1.gesina_scheduled_task_observation_days AS anon_1_gesina_scheduled_task_observation_days, anon_1.gesina_scheduled_task_forecast_days AS anon_1_gesina_scheduled_task_forecast_days, anon_1.gesina_scheduled_task_calibration_id AS anon_1_gesina_scheduled_task_calibration_id, anon_1.gesina_scheduled_task_calibration_id_for_simulations AS anon_1_gesina_scheduled_task_calibration_id_for_simulatio_1, geometry_1.id AS geometry_1_id, geometry_1.name AS geometry_1_name, geometry_1.description AS geometry_1_description, geometry_1.created_at AS geometry_1_created_at, geometry_1.user_id AS geometry_1_user_id, user_1.password AS user_1_password, geometry_2.id AS geometry_2_id, geometry_2.name AS geometry_2_name, geometry_2.description AS geometry_2_description, geometry_2.created_at AS geometry_2_created_at, geometry_2.user_id AS geometry_2_user_id, execution_plan_output_1.river AS execution_plan_output_1_river, execution_plan_output_1.reach AS execution_plan_output_1_reach, execution_plan_output_1.river_stat AS execution_plan_output_1_river_stat, execution_plan_output_1.execution_plan_id AS execution_plan_output_1_execution_plan_id, execution_plan_output_1.stage_series_id AS execution_plan_output_1_stage_series_id, execution_plan_output_1.flow_series_id AS execution_plan_output_1_flow_series_id, execution_plan_output_1.stage_datum AS execution_plan_output_1_stage_datum, execution_plan_1.id AS execution_plan_1_id, execution_plan_1.plan_name AS execution_plan_1_plan_name, execution_plan_1.geometry_id AS execution_plan_1_geometry_id, execution_plan_1.user_id AS execution_plan_1_user_id, execution_plan_1.start_datetime AS execution_plan_1_start_datetime, execution_plan_1.end_datetime AS execution_plan_1_end_datetime, execution_plan_1.created_at AS execution_plan_1_created_at, execution_plan_1.status AS execution_plan_1_status, user_notification_1.id AS user_notification_1_id, user_notification_1.seen AS user_notification_1_seen, user_notification_1.user_id AS user_notification_1_user_id, user_notification_1.execution_plan_id AS user_notification_1_execution_plan_id, user_1.id AS user_1_id, user_1.first_name AS user_1_first_name, user_1.last_name AS user_1_last_name, user_1.email AS user_1_email, user_1.admin_role AS user_1_admin_role, user_1.active AS user_1_active, user_1.session_id AS user_1_session_id, initial_flow_1.id AS initial_flow_1_id, initial_flow_1.scheduled_task_id AS initial_flow_1_scheduled_task_id, initial_flow_1.river AS initial_flow_1_river, initial_flow_1.reach AS initial_flow_1_reach, initial_flow_1.river_stat AS initial_flow_1_river_stat, initial_flow_1.flow AS initial_flow_1_flow, border_condition_1.id AS border_condition_1_id, border_condition_1.scheduled_task_id AS border_condition_1_scheduled_task_id, border_condition_1.river AS border_condition_1_river, border_condition_1.reach AS border_condition_1_reach, border_condition_1.river_stat AS border_condition_1_river_stat, border_condition_1.interval AS border_condition_1_interval, border_condition_1.type AS border_condition_1_type, border_condition_1.series_id AS border_condition_1_series_id, plan_series_1.id AS plan_series_1_id, plan_series_1.river AS plan_series_1_river, plan_series_1.reach AS plan_series_1_reach, plan_series_1.river_stat AS plan_series_1_river_stat, plan_series_1.stage_series_id AS plan_series_1_stage_series_id, plan_series_1.flow_series_id AS plan_series_1_flow_series_id, plan_series_1.scheduled_task_id AS plan_series_1_scheduled_task_id, plan_series_1.stage_datum AS plan_series_1_stage_datum 
	    FROM (SELECT gesina.scheduled_task.metadata AS gesina_scheduled_task_metadata, gesina.scheduled_task.id AS gesina_scheduled_task_id, gesina.scheduled_task.name AS gesina_scheduled_task_name, gesina.scheduled_task.description AS gesina_scheduled_task_description, gesina.scheduled_task.frequency AS gesina_scheduled_task_frequency, gesina.scheduled_task.created_at AS gesina_scheduled_task_created_at, gesina.scheduled_task.start_datetime AS gesina_scheduled_task_start_datetime, gesina.scheduled_task.enabled AS gesina_scheduled_task_enabled, gesina.scheduled_task.geometry_id AS gesina_scheduled_task_geometry_id, gesina.scheduled_task.user_id AS gesina_scheduled_task_user_id, gesina.scheduled_task.start_condition_type AS gesina_scheduled_task_start_condition_type, gesina.scheduled_task.observation_days AS gesina_scheduled_task_observation_days, gesina.scheduled_task.forecast_days AS gesina_scheduled_task_forecast_days, gesina.scheduled_task.calibration_id AS gesina_scheduled_task_calibration_id, gesina.scheduled_task.calibration_id_for_simulations AS gesina_scheduled_task_calibration_id_for_simulations 
	    FROM gesina.scheduled_task 
	    WHERE gesina.scheduled_task.id = '2' 
	     LIMIT 1) AS anon_1 LEFT OUTER JOIN gesina.geometry AS geometry_1 ON geometry_1.id = anon_1.gesina_scheduled_task_geometry_id LEFT OUTER JOIN gesina."user" AS user_1 ON user_1.id = anon_1.gesina_scheduled_task_user_id LEFT OUTER JOIN gesina.user_notification AS user_notification_1 ON user_1.id = user_notification_1.user_id AND user_notification_1.seen = false LEFT OUTER JOIN gesina.execution_plan AS execution_plan_1 ON execution_plan_1.id = user_notification_1.execution_plan_id LEFT OUTER JOIN gesina.geometry AS geometry_2 ON geometry_2.id = execution_plan_1.geometry_id LEFT OUTER JOIN gesina.execution_plan_output AS execution_plan_output_1 ON execution_plan_1.id = execution_plan_output_1.execution_plan_id LEFT OUTER JOIN gesina.initial_flow AS initial_flow_1 ON anon_1.gesina_scheduled_task_id = initial_flow_1.scheduled_task_id LEFT OUTER JOIN gesina.border_condition AS border_condition_1 ON anon_1.gesina_scheduled_task_id = border_condition_1.scheduled_task_id LEFT OUTER JOIN gesina.plan_series AS plan_series_1 ON anon_1.gesina_scheduled_task_id = plan_series_1.scheduled_task_id ORDER BY user_notification_1.id DESC, initial_flow_1.id, border_condition_1.id, plan_series_1.id
    2023-12-13 18:48:51.579 UTC [118] FATAL:  connection to client lost
    2023-12-13 18:48:51.579 UTC [118] STATEMENT:  SELECT anon_1.gesina_scheduled_task_metadata AS anon_1_gesina_scheduled_task_metadata, anon_1.gesina_scheduled_task_id AS anon_1_gesina_scheduled_task_id, anon_1.gesina_scheduled_task_name AS anon_1_gesina_scheduled_task_name, anon_1.gesina_scheduled_task_description AS anon_1_gesina_scheduled_task_description, anon_1.gesina_scheduled_task_frequency AS anon_1_gesina_scheduled_task_frequency, anon_1.gesina_scheduled_task_created_at AS anon_1_gesina_scheduled_task_created_at, anon_1.gesina_scheduled_task_start_datetime AS anon_1_gesina_scheduled_task_start_datetime, anon_1.gesina_scheduled_task_enabled AS anon_1_gesina_scheduled_task_enabled, anon_1.gesina_scheduled_task_geometry_id AS anon_1_gesina_scheduled_task_geometry_id, anon_1.gesina_scheduled_task_user_id AS anon_1_gesina_scheduled_task_user_id, anon_1.gesina_scheduled_task_start_condition_type AS anon_1_gesina_scheduled_task_start_condition_type, anon_1.gesina_scheduled_task_observation_days AS anon_1_gesina_scheduled_task_observation_days, anon_1.gesina_scheduled_task_forecast_days AS anon_1_gesina_scheduled_task_forecast_days, anon_1.gesina_scheduled_task_calibration_id AS anon_1_gesina_scheduled_task_calibration_id, anon_1.gesina_scheduled_task_calibration_id_for_simulations AS anon_1_gesina_scheduled_task_calibration_id_for_simulatio_1, geometry_1.id AS geometry_1_id, geometry_1.name AS geometry_1_name, geometry_1.description AS geometry_1_description, geometry_1.created_at AS geometry_1_created_at, geometry_1.user_id AS geometry_1_user_id, user_1.password AS user_1_password, geometry_2.id AS geometry_2_id, geometry_2.name AS geometry_2_name, geometry_2.description AS geometry_2_description, geometry_2.created_at AS geometry_2_created_at, geometry_2.user_id AS geometry_2_user_id, execution_plan_output_1.river AS execution_plan_output_1_river, execution_plan_output_1.reach AS execution_plan_output_1_reach, execution_plan_output_1.river_stat AS execution_plan_output_1_river_stat, execution_plan_output_1.execution_plan_id AS execution_plan_output_1_execution_plan_id, execution_plan_output_1.stage_series_id AS execution_plan_output_1_stage_series_id, execution_plan_output_1.flow_series_id AS execution_plan_output_1_flow_series_id, execution_plan_output_1.stage_datum AS execution_plan_output_1_stage_datum, execution_plan_1.id AS execution_plan_1_id, execution_plan_1.plan_name AS execution_plan_1_plan_name, execution_plan_1.geometry_id AS execution_plan_1_geometry_id, execution_plan_1.user_id AS execution_plan_1_user_id, execution_plan_1.start_datetime AS execution_plan_1_start_datetime, execution_plan_1.end_datetime AS execution_plan_1_end_datetime, execution_plan_1.created_at AS execution_plan_1_created_at, execution_plan_1.status AS execution_plan_1_status, user_notification_1.id AS user_notification_1_id, user_notification_1.seen AS user_notification_1_seen, user_notification_1.user_id AS user_notification_1_user_id, user_notification_1.execution_plan_id AS user_notification_1_execution_plan_id, user_1.id AS user_1_id, user_1.first_name AS user_1_first_name, user_1.last_name AS user_1_last_name, user_1.email AS user_1_email, user_1.admin_role AS user_1_admin_role, user_1.active AS user_1_active, user_1.session_id AS user_1_session_id, initial_flow_1.id AS initial_flow_1_id, initial_flow_1.scheduled_task_id AS initial_flow_1_scheduled_task_id, initial_flow_1.river AS initial_flow_1_river, initial_flow_1.reach AS initial_flow_1_reach, initial_flow_1.river_stat AS initial_flow_1_river_stat, initial_flow_1.flow AS initial_flow_1_flow, border_condition_1.id AS border_condition_1_id, border_condition_1.scheduled_task_id AS border_condition_1_scheduled_task_id, border_condition_1.river AS border_condition_1_river, border_condition_1.reach AS border_condition_1_reach, border_condition_1.river_stat AS border_condition_1_river_stat, border_condition_1.interval AS border_condition_1_interval, border_condition_1.type AS border_condition_1_type, border_condition_1.series_id AS border_condition_1_series_id, plan_series_1.id AS plan_series_1_id, plan_series_1.river AS plan_series_1_river, plan_series_1.reach AS plan_series_1_reach, plan_series_1.river_stat AS plan_series_1_river_stat, plan_series_1.stage_series_id AS plan_series_1_stage_series_id, plan_series_1.flow_series_id AS plan_series_1_flow_series_id, plan_series_1.scheduled_task_id AS plan_series_1_scheduled_task_id, plan_series_1.stage_datum AS plan_series_1_stage_datum 
	    FROM (SELECT gesina.scheduled_task.metadata AS gesina_scheduled_task_metadata, gesina.scheduled_task.id AS gesina_scheduled_task_id, gesina.scheduled_task.name AS gesina_scheduled_task_name, gesina.scheduled_task.description AS gesina_scheduled_task_description, gesina.scheduled_task.frequency AS gesina_scheduled_task_frequency, gesina.scheduled_task.created_at AS gesina_scheduled_task_created_at, gesina.scheduled_task.start_datetime AS gesina_scheduled_task_start_datetime, gesina.scheduled_task.enabled AS gesina_scheduled_task_enabled, gesina.scheduled_task.geometry_id AS gesina_scheduled_task_geometry_id, gesina.scheduled_task.user_id AS gesina_scheduled_task_user_id, gesina.scheduled_task.start_condition_type AS gesina_scheduled_task_start_condition_type, gesina.scheduled_task.observation_days AS gesina_scheduled_task_observation_days, gesina.scheduled_task.forecast_days AS gesina_scheduled_task_forecast_days, gesina.scheduled_task.calibration_id AS gesina_scheduled_task_calibration_id, gesina.scheduled_task.calibration_id_for_simulations AS gesina_scheduled_task_calibration_id_for_simulations 
	    FROM gesina.scheduled_task 
	    WHERE gesina.scheduled_task.id = '2' 
	     LIMIT 1) AS anon_1 LEFT OUTER JOIN gesina.geometry AS geometry_1 ON geometry_1.id = anon_1.gesina_scheduled_task_geometry_id LEFT OUTER JOIN gesina."user" AS user_1 ON user_1.id = anon_1.gesina_scheduled_task_user_id LEFT OUTER JOIN gesina.user_notification AS user_notification_1 ON user_1.id = user_notification_1.user_id AND user_notification_1.seen = false LEFT OUTER JOIN gesina.execution_plan AS execution_plan_1 ON execution_plan_1.id = user_notification_1.execution_plan_id LEFT OUTER JOIN gesina.geometry AS geometry_2 ON geometry_2.id = execution_plan_1.geometry_id LEFT OUTER JOIN gesina.execution_plan_output AS execution_plan_output_1 ON execution_plan_1.id = execution_plan_output_1.execution_plan_id LEFT OUTER JOIN gesina.initial_flow AS initial_flow_1 ON anon_1.gesina_scheduled_task_id = initial_flow_1.scheduled_task_id LEFT OUTER JOIN gesina.border_condition AS border_condition_1 ON anon_1.gesina_scheduled_task_id = border_condition_1.scheduled_task_id LEFT OUTER JOIN gesina.plan_series AS plan_series_1 ON anon_1.gesina_scheduled_task_id = plan_series_1.scheduled_task_id ORDER BY user_notification_1.id DESC, initial_flow_1.id, border_condition_1.id, plan_series_1.id
    2023-12-13 18:48:52.837 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:48:52.874 UTC [120] ERROR:  relation "yoyo_lock" already exists
    2023-12-13 18:48:52.874 UTC [120] STATEMENT:  CREATE TABLE "yoyo_lock" (locked INT DEFAULT 1, ctime TIMESTAMP,pid INT NOT NULL,PRIMARY KEY (locked))
    2023-12-13 18:48:52.887 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:48:53.193 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:48:53.193 UTC [120] ERROR:  table "yoyo_tmp_dNZGQVbUU4" does not exist
    2023-12-13 18:48:53.193 UTC [120] STATEMENT:  DROP TABLE "yoyo_tmp_dNZGQVbUU4"
    2023-12-13 18:48:53.278 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:48:53.314 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:48:53.315 UTC [120] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.051 UTC [121] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.078 UTC [121] ERROR:  relation "yoyo_lock" already exists
    2023-12-13 18:49:23.078 UTC [121] STATEMENT:  CREATE TABLE "yoyo_lock" (locked INT DEFAULT 1, ctime TIMESTAMP,pid INT NOT NULL,PRIMARY KEY (locked))
    2023-12-13 18:49:23.078 UTC [121] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.224 UTC [121] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.239 UTC [121] ERROR:  table "yoyo_tmp_VQNP33Wygs" does not exist
    2023-12-13 18:49:23.239 UTC [121] STATEMENT:  DROP TABLE "yoyo_tmp_VQNP33Wygs"
    2023-12-13 18:49:23.241 UTC [121] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.268 UTC [121] WARNING:  there is already a transaction in progress
    2023-12-13 18:49:23.269 UTC [121] WARNING:  there is already a transaction in progress

**Comment by azulzaietz** [comment]
Hola Juan, cómo estás?

Nos podrías aclarar por favor qué estabas intentando modificar en la corrida programada? Qué campo o qué parametro. Para poder reproducir el error.

Gracias!

**Comment by jbianchi81** [comment]
> Hola Juan, cómo estás?
> 
> Nos podrías aclarar por favor qué estabas intentando modificar en la corrida programada? Qué campo o qué parametro. Para poder reproducir el error.
> 
> Gracias!

La frecuencia de ejecución

**Comment by azulzaietz** [comment]
Juan, no estoy pudiendo reproducir el error. A mi me deja editar la frecuencia de ejecución sin problemas.

Podrías seguir estos pasos para mostrarme los valores de tu tabla yoyo_lock para entender mejor qué está pasando?

1. Correr en la terminal el comando ```sudo docker ps```
2. Copiar el Container ID
3. Ejecutar en la terminal la siguiente línea, reemplazando Container ID por el número copiado en el paso anterior: ```sudo docker exec -it <Container ID> psql -U user -d main```
4. Una vez conectado a la base de datos ejecutar: ```SELECT * FROM yoyo_lock;```
5. Sacar un screenshot para ver qué valores tiene la tabla

Gracias!

**Comment by cerobpm** [comment]
main=# select * from yoyo_lock;
 locked | ctime | pid 
--------+-------+-----
(0 rows)

**Comment by azulzaietz** [comment]
A vos te sigue pasando? Osea si ahora intentas editar la frecuencia te tira el mismo error?

**Comment by cerobpm** [comment]
No pasa con la corrida programada por defecto, pero no logro crear una nueva corrida programada. Pasa esto cuando le doy guardar:
![image](https://github.com/jbianchi81/gesina/assets/40410912/aee52bc9-cc5f-44f7-9204-500540171b15)
Además, no se está ejecutando la corrida programada por defecto, a pesar de que le modifiqué la frecuencia de ejecución a 5 minutos

**Comment by azulzaietz** [comment]
Vayamos de a un problema a la vez :)

Queres mandarme por mail en un Drive los archivos con los que estás intentado crear una corrida programada para ver por qué no te deja crearla? Así puedo reproducir el error en mi computadora y arreglarlo.

Con los archivos que nos pasaste hace un tiempo en el siguiente Drive: https://drive.google.com/drive/folders/1_Z_rNfa2DfLRpiXSH5H4zcHtL8RASL1c. Tuve que hacer una modificación al código para poder usarlos. Con el código como estaba solamente aceptaba archivos .csv que tuviera únicamente las columnas que usa el programa. Ahora con el cambio que agregué, es necesario que estén las columnas que usa el programa en el orden correcto, pero si luego hay más columnas no afecta a la creación de la corrida programada. Con esos archivos, el archivo salidas.csv tenía una columna extra, por eso pude identificar el error y resolverlo.

Queres pasarme los archivos nuevos con los que estás intentando crear una corrida programada para que pueda analizarlo? 

El error que me mostras es un error de Front end, pero actualmente a mi no me pasa, yo puedo crear corridas programadas. Por eso necesitaría que me muestres los valores y archivos que estás intentando cargar para poder reproducirlo de mi lado.

Una vez que logremos que puedas crear la corrida programada nos fijamos si se ejecuta o no y por qué. Te parece?

**Comment by cerobpm** [comment]
Hola,
Ahora pude crear la corrida programada. Usé los archivos del Drive que les compartí y los parámetros:
- id de calibrado: 487
- frecuencia de ejecución: 5
- cantidad de días previos observados: 30
- cantidad de días de pronóstico: 4
- ID de calibrados para las simulaciones: 288
Se generan los execution_plan, pero quedan pendientes:
![image](https://github.com/jbianchi81/gesina/assets/40410912/7dafb058-6783-4550-a87e-97dafdb44181)

No llegan a ejecutarse en la máquina virtual. Vi este error en el log del scheduler que puede estar relacionado:

    ERROR:apscheduler.executors.default:Job "ScheduledTaskJob.simulate (trigger: interval[0:05:00], next run at: 2024-02-15 13:24:50 UTC)" raised an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/minio/helpers.py", line 219, in check_non_empty_string
        if not string.strip():
    AttributeError: 'NoneType' object has no attribute 'strip'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/src/src/scheduler.py", line 85, in simulate
        execution_plan = execution_plan_service.create_from_scheduler(
      File "/app/src/service/execution_plan_service.py", line 89, in create_from_scheduler
        execution_plan = create(
      File "/app/src/service/execution_plan_service.py", line 187, in create
        file_storage_service.copy_execution_file(restart_name, execution_plan_id,restart_file_name)
      File "/app/src/service/file_storage_service.py", line 190, in copy_execution_file
        minio_client.copy_object(ROOT_BUCKET, minio_path, CopySource(ROOT_BUCKET, file_to_copy))
      File "/usr/local/lib/python3.10/site-packages/minio/api.py", line 1237, in copy_object
        stat = self.stat_object(
      File "/usr/local/lib/python3.10/site-packages/minio/api.py", line 1853, in stat_object
        check_non_empty_string(object_name)
      File "/usr/local/lib/python3.10/site-packages/minio/helpers.py", line 222, in check_non_empty_string
        raise TypeError() from exc
    TypeError

Vos pudiste ejecutar la corrida programada?

**Comment by azulzaietz** [comment]
hola Juan, buenísimo.

El cambio para poder usar los archivos del drive todavía no estaba subido al repo igual. Modificaste el archivo de salidas.csv para que solo tuviera las columnas necesarias? O te dejó igual?

También tengo otra duda, por qué hay tantos planes de ejecución iguales? Eso está bien? Usaste la funcionalidad de copiar un plan de ejecución?

Con respecto a correr la corrida programada, todavía no probé. Pruebo y te aviso

**Comment by jbianchi81** [comment]
Respecto al archivo de salidas, no lo modifiqué. 

Respecto a los planes de ejecución iguales, se genera uno cada 5 minutos (frecuencia de ejecución)

**Comment by azulzaietz** [comment]
Juan, me confirmas que el archivo de salidas.csv que usaste tenga estas columnas? 
<img width="612" alt="image" src="https://github.com/jbianchi81/gesina/assets/39175621/6574f955-fdb9-428a-8c9a-247990d5dcd9">

Teoricamente la columna stage_datum está de más y te debería tirar un error sin el fix del código. Me parece raro que te haya dejado. Me confirmas eso?

Con respeto a que los planes de ejecución no se ejecutan luego de crearse, pregunto por las dudas, tenes habilitada la ejecución, no? El botón que está justo arriba del "Guardar":

<img width="1726" alt="image" src="https://github.com/jbianchi81/gesina/assets/39175621/0adfe710-f4a1-44d0-afc5-3209dd826185">

**Comment by cerobpm** [comment]
Te confirmo que son esas las columnas del archivo salidas.csv. Y que está habilitada la ejecución.

**Comment by cerobpm** [comment]
Ahora veo que no había aceptado el archivo salidas.csv. Le saqué esa columna y lo subí, ahora lo aceptó.

**Comment by cerobpm** [comment]
Parece ser que las tareas se crean pero quedan "pendientes", hay que encolarlas a mano en /execution_plan/list. Deberían ejecutarse automáticamente

**Comment by cerobpm** [comment]
Otra cuestión, había unas modificaciones que había hecho yo, por ejemplo el agregado de la columna 'stage_datum', que parece que no están en esta rama, y son necesarias: https://github.com/jbianchi81/gesina/compare/fix_date_parsing...adjust_end_date

**Comment by azulzaietz** [comment]
Hola Juan. Perfecto, me parecía raro que te tomara el archivo. 

Vamos a revisar el tema de la ejecución de las tareas programadas y agregar tus cambios a nuestro repo!

Gracias! Te escribimos con novedades y/o preguntas :)

**Comment by azulzaietz** [comment]
Hola Juan! Con los cambios que hicimos me parece que todos estos problemas están resueltos. Queres probarlo para confirmarnos? 
Gracias y saludos!

**Comment by cerobpm** [comment]
Persiste el problema. Al ir generando corridas la aplicación se va volviendo más lenta hasta que ya el frontend empieza a dar timeouts.

**Comment by azulzaietz** [comment]
Hola Juan, cómo estás?

Podríamos agendar una reunión así nos mostras el problema en vivo? Algún día que estés con la computadora linux donde tenes instalado el proyecto. Así nos podes comprartir pantalla y lo podemos ver juntos. Nos gustaría verlo para saber cómo reproducirlo y solucionarlo.

Nos avisas cuándo podrías? Algún día de esta semana te queda bien? El jueves a la tarde podría ser. Vas a estar con la computadora del instituto?

Gracias!

**Comment by cerobpm** [comment]
Hola,

Yo estoy miércoles y viernes en el Instituto. Tendría que ser antes de las 18hs.

**Comment by azulzaietz** [comment]
Dale! Mañana a las 14 te queda bien?

**Comment by cerobpm** [comment]
Dale, perfecto

**Comment by federicoburman** [comment]
@cerobpm En el front cuando se muestran las listas de schedule task y execution plans ahora se obtienen solo las columnas requeridas. Ya no tarda en cargar. El timeout era solo sobre ese caso o ocurria en otro lugar?
Si era solo ahi, se puede cerrar el issue

**Comment by cerobpm** [comment]
@federicoburman, también ocurre con:
- GET http://localhost:5001/view/schedule_tasks/3 (editar corrida programada)
- POST http://localhost:5001/view/schedule_tasks/3 (guardar corrida programada)
- POST http://localhost:5001/schedule_task/copy/3 (copiar corrida programada)
