### ISSUE TITLE
Scheduler: ImportError: cannot import name 'check_duplicate_output_series' from partially initialized module 'src.service.plan_series_service' (most likely due to a circular import) (/app/src/service/plan_series_service.py)

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#24]
No levanta scheduler
 
    $ docker logs gesina-scheduler-1  
  
    Traceback (most recent call last):
      File "/src/src/scheduler.py", line 15, in <module>
        from src.service.schedule_task_service import get_schedule_task_config
      File "/app/src/service/schedule_task_service.py", line 14, in <module>
        from src.service import plan_series_service
      File "/app/src/service/plan_series_service.py", line 4, in <module>
        from src.controller.schemas import PLAN_SERIES_SCHEMA
      File "/app/src/controller/__init__.py", line 2, in <module>
        from src.controller.view_controller import VIEW_BLUEPRINT
      File "/app/src/controller/view_controller.py", line 20, in <module>
        from src.service.plan_series_service import check_duplicate_output_series
    ImportError: cannot import name 'check_duplicate_output_series' from partially initialized module 'src.service.plan_series_service' (most likely due to a circular import) (/app/src/service/plan_series_service.py)

@manulon
@azulzaietz
@federicoburman

**Comment by federicoburman** [comment]
Lo miro!

**Comment by federicoburman** [comment]
@cerobpm @jbianchi81 Arreglado!
